apiVersion: v1
kind: Service
metadata:
  name: {{ include "springjpaoracle.fullname" . }}
  labels:
    {{- include "springjpaoracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    {{- include "springjpaoracle.selectorLabels" . | nindent 4 }}
