apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-xe.fullname" . }}
  labels:
    {{- include "oracle-xe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1521
      protocol: TCP
      name: jdbc
  selector:
    {{- include "oracle-xe.selectorLabels" . | nindent 4 }}
