application:
  keycloak_auth_root_uri: http://localhost:8088/auth/realms/springjpaoracle
  keycloak_admin_root_uri: http://localhost:8088/auth/admin/realms/springjpaoracle/
  client_id: springjpaoracle
  client_secret: w8t76w34563ty7hegvsiety8934cv3456yu3o5c4
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/auth/realms/springjpaoracle
          jwk-set-uri: http://localhost:8088/auth/realms/springjpaoracle/protocol/openid-connect/certs
  application:
    name: producer-service
  cloud:
    function:
      definition: studentRegistryInput;studentDeleteInput
    stream:
      bindings:
        studentDeleteInput-in-0:
          destination: student_delete.topic
          group: springjpaoracle-consumer
        studentRegistryInput-in-0:
          destination: students.topic
          group: springjpaoracle-consumer
        register-student-output:
          destination: students.topic
  #      default:
  #        contentType: application/json
  rabbitmq:
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_HOST:localhost}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: false
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: "jdbc:oracle:thin:@localhost:${ORACLE_PORT:1521}:XE"
    username: testuser
    password: testpassword
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      initialization-fail-timeout: -1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessstate,cacheCheck
  metrics:
    enable:
      jvm: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 1ms, 5ms
